version: 2.1

orbs:
  architect: giantswarm/architect@0.8.4

workflows:
  test:
    jobs:
      - architect/go-build:
          name: go-build
          binary: gg
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
